version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - oracle
  oracle:
    image: sath89/oracle-12c
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
