--Eliminar table
DROP TABLE Assignment

-- Crear la tabla
CREATE TABLE Assignment (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Title VARCHAR2(255) NOT NULL,
    Description VARCHAR2(1000),
    CreationDate DATE DEFAULT SYSDATE,
    DueDate DATE,
    Status VARCHAR2(50),
    PRIMARY KEY (Id)
);

-- Insertar datos de ejemplo
INSERT INTO Assignment (Title, Description, CreationDate, DueDate, Status) VALUES 
('Complete project report', 'Finish and submit the project report by the end of the week.', SYSDATE, SYSDATE + 7, 'In Progress');

INSERT INTO Assignment (Title, Description, CreationDate, DueDate, Status) VALUES 
('Team meeting', 'Monthly meeting to discuss project progress and next steps.', SYSDATE, SYSDATE + 2, 'Scheduled');

INSERT INTO Assignment (Title, Description, CreationDate, DueDate, Status) VALUES 
('Code review', 'Review code for the latest feature addition.', SYSDATE, SYSDATE + 1, 'Pending');

CREATE TABLE Users (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Username VARCHAR2(50) NOT NULL,
    Password VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    FirstName VARCHAR2(50),
    LastName VARCHAR2(50),      
    PRIMARY KEY (Id)
);

INSERT INTO Users ( Username, Password, Email, FirstName, LastName)
VALUES ('edwin', 'edwinTest', 'edwin@gmail.com', 'Edwin', 'Tejada');
